import { Meteor } from 'meteor/meteor';
import { StudyLists } from '../../api/studyLists/studyLists.js'

Meteor.startup(() => {
  // Random data population onto MongoDB
  if(StudyLists.find().count() === 0){
    for(var i=0; i< 1000; i++){
      var someDay = Math.round(1 + Math.random()*30);
      var someMonth = Math.round(0 + Math.random()*11);
      var someYear = someMonth == 11 ? 2016: 2017; 
      var randomDate = new Date(someYear, someMonth, someDay);
      var randomStudyField = "s" + Math.round(1 + Math.random()*6);
      var filler = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed elit tortor. Sed \
                    eros lectus, porttitor a pellentesque nec, finibus a mauris. Aliquam maximus finibus turpis, \
                    vel laoreet eros imperdiet eu. Curabitur eu suscipit libero. Aliquam scelerisque ipsum hendrerit \
                    velit venenatis, ac consectetur nisl tempus. Maecenas iaculis felis egestas leo dignissim, ut eleifend \
                    lectus rhoncus. Suspendisse mattis cursus arcu, quis imperdiet orci pellentesque non. Duis suscipit felis \
                    quis nulla mollis mattis. Donec vitae auctor felis. Nulla pretium augue et justo rhoncus, bibendum consequat \
                    sem fermentum. Aliquam pulvinar ligula vitae consequat semper. Nulla molestie odio venenatis, ullamcorper nunc \
                    nec, ullamcorper odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. \
                    Mauris nisi lectus, tincidunt ut eros eu, ultrices rhoncus urna. Vestibulum non gravida nulla. Sed vitae tincidunt \
                    enim, non ultricies arcu. Morbi porta tincidunt sem, non metus. \
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec erat turpis. Nulla ut tempus justo. Maecenas id risus consequat, varius nisi a, accumsan nisl. Suspendisse vulputate feugiat magna, nec volutpat lectus ornare sit amet. Pellentesque finibus, magna sit amet tempus porttitor, nunc nulla viverra ipsum, quis vestibulum lectus sapien non sem. Cras sed enim urna. In non lacus eget leo pulvinar egestas.\
        Proin a nisl malesuada leo bibendum scelerisque a eget nulla. Praesent blandit quam nec turpis venenatis, sed blandit lacus hendrerit. Duis sed auctor lorem. Nulla facilisi. Etiam est purus, bibendum quis pulvinar quis, ultrices ut quam. Cras a nisl eget libero porttitor dapibus. Nullam dolor nisl, dictum sed ultrices efficitur, ornare in nunc. In suscipit sapien id lobortis condimentum.\
        Curabitur efficitur nisi egestas, vestibulum nisl ac, vehicula odio. Maecenas elementum justo sit amet ligula dapibus, non venenatis mi efficitur. Maecenas eu pharetra ligula. Etiam eu urna egestas tortor posuere interdum. Praesent est quam, ornare ut ante fermentum, interdum scelerisque augue. Nam dolor ante, luctus a turpis consequat, aliquet pellentesque mi. Ut suscipit cursus tellus, aliquet posuere libero suscipit vulputate. Mauris tincidunt nisl vitae nulla malesuada porttitor.\
        In posuere tincidunt nulla, quis sagittis velit tempus faucibus. Phasellus cursus dolor sit amet purus iaculis ultricies. Nulla id elementum nunc. In dictum pretium orci, vel finibus erat sollicitudin in. Quisque consequat sapien vel velit pharetra, et ornare neque porttitor. Aliquam mauris justo, suscipit ut tortor at, dapibus dapibus mauris. Duis tincidunt eros neque, a eleifend ante tempor quis. In elementum elit sed lorem commodo ultrices. Cras cursus risus non mollis pretium.\
        In a nisl a ipsum laoreet commodo. Fusce imperdiet, augue in elementum scelerisque, sem quam venenatis sapien, at finibus nisl magna at nulla. Pellentesque venenatis diam nec metus lobortis commodo. Praesent auctor, dolor sit amet auctor commodo, massa erat imperdiet magna, ac ultrices massa felis suscipit lorem. Quisque nunc ligula, facilisis nec magna et, tristique cursus nisl. Suspendisse convallis diam ac mi rhoncus tempor. Etiam vitae quam faucibus augue lacinia sagittis.\
        Ut sagittis diam sit amet volutpat ultrices. Aliquam erat volutpat. Aliquam et malesuada augue. Phasellus fermentum ut tellus ut consequat. Integer auctor nibh blandit pulvinar fringilla. Curabitur quis nunc orci. Mauris ac dolor dapibus, eleifend ante id, mollis magna. Proin fringilla luctus interdum. Integer vestibulum vestibulum ullamcorper. Donec non gravida nibh. Mauris gravida rhoncus dui.\
        Pellentesque efficitur, mi et ultricies tristique, ligula elit elementum metus, eu accumsan justo arcu in mauris. Pellentesque facilisis dui arcu, id condimentum orci iaculis nec. Sed eleifend mollis mauris, sollicitudin consectetur nisi aliquam sit amet. Nulla fringilla hendrerit magna, id tempor velit tincidunt a. Nunc cursus leo nec sapien placerat, et sodales velit interdum. Proin id purus sed arcu mollis laoreet at non est. Donec bibendum, justo sollicitudin egestas egestas, leo ipsum tempus dolor, at faucibus turpis nisi a mi. Morbi sed dui ac augue bibendum cursus eget sit amet lorem. In ac neque purus. Vivamus consequat et risus sed scelerisque. Sed pretium magna vel libero convallis, at ornare turpis imperdiet.\
        Cras accumsan fermentum justo, sollicitudin maximus risus. Ut eu justo odio. Sed tincidunt turpis ut rutrum suscipit. Nulla finibus nisl posuere est suscipit, quis congue est consectetur. Nunc laoreet porttitor dui tincidunt vulputate. Etiam ut massa a ex euismod convallis a ac ex. Donec venenatis massa ac pellentesque gravida. Donec gravida dapibus tellus, id dignissim ex. Fusce a dolor porta, cursus erat non, finibus sapien. Aliquam consequat lorem metus. Ut id bibendum magna, ut facilisis nisi.\
        Suspendisse pharetra sem nec ultricies blandit. Vestibulum egestas enim enim, tempus lacinia orci finibus ut. Vestibulum a diam diam. Quisque at semper diam. Suspendisse potenti. Nullam tempor urna id tincidunt volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel maximus tortor. Pellentesque luctus hendrerit mauris a condimentum. Interdum et malesuada fames ac ante ipsum primis in faucibus.\
        Nunc pretium mauris et dui mattis, eget imperdiet ipsum venenatis. Vivamus sodales sit amet purus in mollis. Praesent sit amet mi eu odio scelerisque euismod. Vestibulum vitae ornare ipsum. Mauris ultrices libero neque, ac malesuada ante luctus eu. Sed aliquam velit sit amet mi vestibulum vestibulum. Proin nisl justo, vestibulum in ullamcorper sed, placerat a massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam efficitur vitae massa nec fringilla. Proin fringilla laoreet porta. Morbi commodo nisl eu dui ornare, ut feugiat ipsum lobortis. Suspendisse sit amet sagittis nisi, a dapibus nunc. Aliquam erat volutpat. Phasellus consequat dapibus congue. Duis nulla urna, hendrerit sit amet felis nec, lacinia facilisis turpis. Suspendisse consequat diam aliquam diam sodales tincidunt.\
        Vestibulum non blandit tellus, ut maximus ex. Morbi consectetur consequat sodales. Fusce malesuada mollis maximus. Aliquam sapien nulla, suscipit vel enim a, congue semper massa. Vestibulum placerat libero sit amet efficitur molestie. Suspendisse non accumsan justo, non cursus nisl. Quisque fringilla dictum nisi quis efficitur.\
        Nunc mattis semper justo. Duis lacus ligula, faucibus eget blandit ac, finibus ut lorem. Ut sed tortor quis libero feugiat vestibulum. In dui ligula, elementum nec libero eget, congue placerat ex. Fusce eget feugiat libero. Nulla lectus quam, elementum a sodales ac, ultricies non dui. Vivamus nec ultrices massa. Praesent lobortis faucibus arcu, non interdum magna blandit id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur consectetur justo nec metus dictum tempor. Proin maximus auctor quam ut fermentum.\
        Pellentesque vitae pulvinar lorem. Donec porta ac dui at cursus. Vivamus pulvinar nibh eget diam bibendum, dapibus sodales sem scelerisque. Proin pretium lorem ipsum, eget euismod purus feugiat nec. Nullam finibus auctor arcu sit amet eleifend. Curabitur finibus ligula consectetur nisi ultricies, id convallis elit placerat. Sed lectus mi, scelerisque in luctus sed, sollicitudin eu magna. Vestibulum in nunc imperdiet orci placerat venenatis id id urna. Sed hendrerit vulputate justo, a maximus tellus sagittis quis.\
        Donec orci lacus, vulputate eget fringilla at, pellentesque sed justo. Ut massa justo, vehicula nec ipsum et, placerat aliquam leo. Suspendisse tortor elit, sollicitudin in finibus eget, condimentum at elit. Sed nisl leo, semper nec mauris sed, consequat molestie erat. Fusce at fringilla justo. Nam et sem odio. Integer pellentesque eu enim vitae facilisis. Nunc nisi libero, dictum eget finibus at, eleifend vel urna. Donec nec finibus odio, eget tempus odio.\
        Phasellus molestie molestie mauris, ut ullamcorper massa tincidunt ut. Aenean et velit nec lectus blandit suscipit. Nam sed arcu est. In hac habitasse platea dictumst. Donec sagittis imperdiet vestibulum. Sed nec lorem ligula. Suspendisse gravida orci orci, vel vestibulum nibh iaculis vitae. Vivamus id ligula sodales, hendrerit sapien ac, iaculis diam.\
        Curabitur est tellus, bibendum et commodo nec, vehicula a justo. Etiam sed aliquam quam. Nullam vel magna eget turpis porttitor viverra. Pellentesque interdum tempor libero, et tristique metus ornare a. Pellentesque tincidunt ipsum nisl, ut facilisis lacus gravida id. Quisque placerat tincidunt enim, a tincidunt mauris. Nam congue a dolor gravida posuere. Curabitur commodo risus vel facilisis fermentum. Pellentesque nec pharetra eros, vulputate aliquam sem. Sed laoreet eu enim non consequat. Donec ultricies mattis purus ac vestibulum. Aliquam et dapibus sem. Vestibulum nec gravida nisl. Vestibulum mattis commodo suscipit.\
        Ut sed fringilla eros. Ut scelerisque risus magna. Suspendisse odio tortor, pellentesque ut lorem ac, posuere rutrum velit. In iaculis non ipsum at vestibulum. Donec nunc urna, pulvinar ac diam sit amet, sollicitudin ultrices dui. Nulla dictum felis in ipsum ultrices molestie vel a erat. Donec magna lorem, lobortis non dui ut, dapibus porta enim. Duis hendrerit varius sem, nec accumsan diam porttitor vel. Morbi eu ipsum commodo, blandit dui eget, gravida nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque nec condimentum lectus, mollis fermentum nibh. Curabitur semper pellentesque mi id posuere. Nunc a aliquet neque, vitae pellentesque lectus. Aenean at purus eu nibh venenatis aliquet.\
        Nullam commodo lorem felis, sit amet vulputate arcu facilisis et. In sem diam, ultrices sed enim faucibus, ultrices lacinia est. Maecenas vitae eros neque. Phasellus ultrices justo eget nulla blandit, non laoreet urna egestas. In eu ligula quis elit viverra mollis sit amet nec lorem. Integer vitae leo imperdiet metus iaculis feugiat. Aliquam tincidunt, turpis venenatis facilisis viverra, diam ipsum aliquet urna, vel laoreet nisl augue eget nunc. Integer laoreet justo at sem finibus, sit amet vehicula magna suscipit. Nam rhoncus eu urna quis lobortis. Fusce scelerisque mi est, ac vehicula enim bibendum eu. Cras sit amet venenatis odio.\
        Integer congue leo sagittis ipsum aliquam, ut elementum tortor consequat. Mauris bibendum posuere lacus, quis tincidunt nunc dictum non. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed non magna ipsum. Suspendisse non nisl eget dolor vestibulum varius ac eu nisi. Nunc lobortis tortor vitae venenatis pretium. Quisque semper, sem eget sollicitudin tempus, velit nulla ultricies erat, non dapibus elit diam vitae felis.\
        Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla vel odio vel ipsum aliquet feugiat non suscipit leo. Sed lacinia blandit tempus. Maecenas sapien lorem, feugiat id nulla non, tincidunt cursus risus. Sed volutpat. ";

      StudyLists.insert({
        startDate: randomDate, 
        startMonth: someMonth, 
        studyField: randomStudyField,
        filler: filler
      });
    }
  }
})
